# Generated by Django 4.2.7 on 2024-11-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='status',
            field=models.CharField(choices=[('activ', 'Действует'), ('delet', 'Удалена')], default='activ', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='history',
            name='status',
            field=models.CharField(choices=[('putin', 'Введён'), ('atwor', 'В работе'), ('compl', 'Завершен'), ('rejec', 'Отклонен'), ('delet', 'Удален')], default='putin', verbose_name='Статус'),
        ),
    ]
