# Generated by Django 4.2.7 on 2024-10-06 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 6, 16, 32, 55, 952307, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
