# Generated by Django 4.2.7 on 2024-11-12 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_film_status_alter_history_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_key', models.CharField(max_length=50, verbose_name='Название')),
                ('name', models.CharField(max_length=50, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Статус фильма',
                'verbose_name_plural': 'Статусы фильмов',
                'db_table': 'film_status',
            },
        ),
        migrations.CreateModel(
            name='HistoryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_key', models.CharField(max_length=50, verbose_name='Название')),
                ('name', models.CharField(max_length=50, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Статус истории',
                'verbose_name_plural': 'Статусы историй',
                'db_table': 'history_status',
            },
        ),
        migrations.AlterField(
            model_name='film',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.filmstatus'),
        ),
        migrations.AlterField(
            model_name='history',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.historystatus'),
        ),
    ]
