# Generated by Django 4.2.7 on 2024-11-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_filmstatus_historystatus_alter_film_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='status',
            field=models.CharField(choices=[(1, 'Действует'), (2, 'Удалена')], default=1, verbose_name='Статус'),
        ),
        migrations.DeleteModel(
            name='FilmStatus',
        ),
    ]
