# Generated by Django 4.2.7 on 2024-11-12 20:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_history_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_key', models.CharField(max_length=50, verbose_name='Название')),
                ('name', models.CharField(max_length=50, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Статус истории',
                'verbose_name_plural': 'Статусы историй',
                'db_table': 'history_status',
            },
        ),
        migrations.AlterField(
            model_name='history',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 12, 20, 48, 10, 273097, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='history',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.historystatus'),
        ),
    ]
