# Generated by Django 4.2.7 on 2024-11-15 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_history_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='status',
            field=models.IntegerField(choices=[(1, 'Действует'), (2, 'Удалена')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='history',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 15, 8, 25, 57, 646704, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.DeleteModel(
            name='FilmStatus',
        ),
    ]
